const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      price: 120,
      countInStock: 10,
      image: '/images/p1.jpg',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'Nike Fit Shirt',
      slug: 'nike-fit-shirt',
      category: 'Shirts',
      price: 120,
      countInStock: 0,
      image: '/images/p2.jpg',
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      price: 25,
      countInStock: 15,
      image: '/images/p3.jpg', // 679px x 829px
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: 4,
      name: 'Adidas Fit Pant',
      slug: 'nike-fit-pant',
      category: 'Pants',
      price: 25,
      countInStock: 0,
      image: '/images/p4.jpg',
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
